-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.title_type
(
    id bigint NOT NULL,
    title character varying(256),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.data
(
    id bigint NOT NULL,
    title bigint,
    text character varying(1000),
    keywords character varying(250)[],
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.data
    ADD FOREIGN KEY (title)
    REFERENCES public.title_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;